### ISSUE TITLE
BlurHash fails to Encode image

### ISSUE THREAD

**Issue by supercmmetry** [MarkusPalcer/blurhash.net#14]
*Error:*

``` 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at Blurhash.ImageSharp.Encoder.ConvertBitmap[T](Image`1 sourceBitmap)
         at Blurhash.ImageSharp.Encoder.Encode(Image`1 image, Int32 componentsX, Int32 componentsY)
```

I found that #13 might fix this. Please merge this PR ASAP.

**Comment by AurelianTimu** [comment]
I have the same issue.
@MarkusPalcer Are there any plans to merge #13 or fix the issue in a different way?

**Comment by MarkusPalcer** [comment]
I just did.

I need a little help with GitHub: I didn't get any notification until you mentioned me in the comment (yeah, I know I took ages to react to that, too)
I didn't even _know_ there was an issue and two PRs ...

Thanks for the contributions though, much appreciated.

**Comment by Toonshorty** [comment]
@MarkusPalcer I'm having this issue with the Blurhash.ImageSharp package from Nuget still. Do you need to push an updated 1.0.1 package to reflect this fix?

**Comment by MarkusPalcer** [comment]
@Toonshorty I changed the package creation from a .nuspec file to integrating the package information in the .csproj and updated the dependency of ImageSharp from the Beta to the release 1.0.0
Thus now the package should be visible NuGet in Version 1.0.1 soon
